version: '3.1'

services:
    boilerplate-ui:
        image: nginx:1-alpine
        restart: always
        depends_on:
            - boilerplate-api
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template.conf
            NGINX_PORT: 80
            APP_BACKEND_URL: http://boilerplate-api
        volumes:
            - ../boilerplate-ui/docker/templates:/etc/nginx/templates
            - ../boilerplate-ui/dist:/opt/app
        ports:
            - 8000:80
    boilerplate-api:
        image: node:16-alpine
        restart: always
        user: "node"
        working_dir: /home/node/app
        command: "yarn start:prod"
        depends_on:
            - boilerplate-api-mongo
        environment:
            PORT: 80
            MONGO_CONNECTION: mongodb://root:pass@boilerplate-api-mongo:27017
            MONGO_DB_NAME: boilerplate
        volumes:
            - ../boilerplate-api:/home/node/app
        ports:
            - 8880:80
    boilerplate-api-mongo:
        image: mongo
        restart: always
        volumes:
            - ./boilerplate-api-mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
            - 8817:27017
    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - boilerplate-api-mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_MONGODB_URL: mongodb://root:pass@boilerplate-api-mongo:27017
        ports:
            - 8888:8081
